services:
  # 1. BACKEND API (.NET)
  backend-api:
    build:
      context: .
      dockerfile: StudyHub.Backend.Api/Dockerfile
    container_name: studyhub-api
    restart: always
    ports:
      - "6789:6789"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:6789
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=studyhub;Uid=studyhub_user;Pwd=123456;Port=3307;
      - ConnectionStrings__MongoDb=mongodb://studyhub_user:123456@mongodb:27018/studyhub?authSource=admin
      - Elasticsearch__Url=http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    container_name: studyhub-elastic
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

volumes:
  elastic_data:
