services:
  # 1. BACKEND API (.NET)
  backend-api:
    image: studyhub-api
    container_name: studyhub-api
    build:
      context: .
      dockerfile: StudyHub.Backend.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongo-db
      - mysql-db
      - elasticsearch

  # 2. MONGODB
  mongo-db:
    image: mongo:8.2.1
    container_name: studyhub-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. MYSQL (Vì bạn có ConnectionStrings:value format kiểu SQL)
  mysql-db:
    image: mysql:8.0.43
    container_name: studyhub-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "studyhub"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 4. ELASTICSEARCH
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    container_name: studyhub-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Tắt bảo mật để chạy dev cho nhanh (http thay vì https)
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Giới hạn RAM để không treo máy
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

volumes:
  mongo_data:
  mysql_data:
  elastic_data:
