export const ROLES = {
  EXTERNAL_STUDENT: "External Student",
  SCHOOL_STUDENT: "School Student",
  SUBJECT_TEACHER: "Subject Teacher",
  HOMEROOM_TEACHER: "Homeroom Teacher",
  HEAD_TEACHER: "Head of Department Teacher",
  QNA_TEACHER: "Q&A Teacher",
  DOCUMENT_MANAGER: "Document Manager",
  QUESTION_MANAGER: "Question Manager",
  FINANCIAL_MANAGER: "Financial Manager",
  UI_MANAGER: "UI Manager",
  MODERATOR: "Moderator",
  SCHOOL_ADMIN: "School Admin",
  ADMIN: "Admin",
};
